### ISSUE TITLE
Issue with pip3 install -e .

### ISSUE THREAD

**Issue by speakerholes** [leggedrobotics/DeLORA#4] opened 2021-05-29 05:09 UTC
Hello, I was curious if anyone could help me with this error? After activating the conda environment and try to run the command pip3 install -e . as shown in the instructions I receive the following error:

![Screenshot from 2021-05-28 22-06-51](https://user-images.githubusercontent.com/78880630/120058649-4c262280-c001-11eb-8be2-7689e5a93c64.png)

When I look into the folder for clone_and_preprocess_darpa_dataset.sh I can not find it anywhere.

**Comment by JustWon** [comment] 2021-05-31 13:01
I have the same issue

**Comment by JustWon** [comment] 2021-06-02 14:41
the command succeeded by getting rid of "clone_and_preprocess_darpa_dataset.sh " from setup.py

**Comment by JustWon** [comment] 2021-06-03 06:53
it works well now. 
![image](https://user-images.githubusercontent.com/14357526/120600629-f4197100-c483-11eb-9709-d676aad361d5.png)

**Comment by nubertj** [comment] 2021-06-17 22:49
Hello @nickhward and @JustWon,
Sorry for not replying earlier. For some reason I did not get any notification for this issue.
Thanks for raising this issue. It was indeed due to some last minute changes I made in the bin/ folder. 

Also great that you found the solution yourself. The issue is resolved in the latest commit:
3d03622e3b8e96a7640d3da107a1937e81aaec1e

**Closed as completed by nubertj** 2021-06-17 22:49 UTC
